---
- hosts: all
  tasks:
    - name: install apache web server
      package:
        name: httpd
        state: latest

    - name: start and enable apache web server
      service:
        name: httpd
        state: started
        enabled: true
